name: untitled
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.6 <4.0.0'
#  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2
  flutter_lints: ^2.0.0
  flutter_local_notifications: ^13.0.0
  google_fonts: ^4.0.4
  http: ^0.13.3
  open_file: ^3.1.0
  path_provider: ^2.0.1
  pdf: ^3.1.0
  plugin_platform_interface: ^2.1.5
  shared_preferences: ^2.0.6
  sqflite: ^2.0.0
  syncfusion_flutter_charts: ^19.2.46
  intl: ^0.17.0

flutter:
  assets:
    - assets/
  uses-material-design: true
